version: '3.6'

services:

  todo-rest:
    build: todo-rest/.
    image: flaviostutz/todo-rest
    ports:
      - "3000:3000"
    restart: always
    environment:
      - BASE_LOCATION_URL=http://localhost:3000

  todo-graphql:
    build: todo-graphql/.
    image: flaviostutz/todo-graphql
    ports:
      - "4000:4000"
    restart: always
    environment:
      - TODO_REST_URL=http://host.docker.internal:3000


