version: '3.6'

services:

  todo-rest:
    build: todo-rest/.
    ports:
      - "3000:3000"
    environment:
      - BASE_LOCATION_URL=http://localhost:3000

  todo-graphql:
    build: todo-graphql-go/.
    ports:
      - "4000:4000"
    environment:
      - TODO_SERVICE_URL=http://host.docker.internal:3000


