// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Todo struct {
	Done  *bool   `json:"done"`
	ID    *string `json:"id"`
	Order *int    `json:"order"`
	Text  *string `json:"text"`
	Title *string `json:"title"`
	User  *string `json:"user"`
}

func (Todo) IsEntity() {}
